### ISSUE TITLE
Cloudflare SSL error 

### ISSUE THREAD

**Issue by royalterra** [wave72/hubchart#2]
Hi I observe your software not support SSL CDN with Cloudflare. I believe Friendica have before support for Cloudflare.

If any domain have DNS in Cloudflare is not possible to add the HUB that also give incorrect geographical location if I deactivate cloudflare and activate afterwards by example some of my hub you say are in Germany or in EEUU when the true all are in France I imagine your software is taking difference locations every time the CDN cache in other place

**Comment by wave1972** [comment]
Hi royalterra, please note that this is the hubchart repository, not hubzilla.
